### ISSUE TITLE
Token Assignment Backup

### ISSUE THREAD

**Issue by robusto** [iamthemovie/legacy#3]
New feature suggestion: Backing up the source node's token assignment can be useful if total node failure occurs.  Just did some quick searching and didn't see anything about it here.  Great project!

http://docs.datastax.com/en/cassandra/2.0/cassandra/operations/ops_snapshot_restore_new_cluster.html

**Comment by iamthemovie** [comment]
Great point. I'll add this to the list. Thank  you!

**Comment by iamthemovie** [comment]
Just out of curiosity, I'm looking at this now and working out whether I should dump the entire ring into a single file on AWS or split it up per node. The output of `nodetool ring` gives IP's over hostnames and I'm also wondering whether I should match up hostnames with IP's too.

**Comment by robusto** [comment]
Either works. I'd say split up the `nodetool ring` output at backup time if you have plans you have for a concurrent "restore" feature. Sets up for a clean workflow and maybe better for tracking changes to individual nodes' token assignment. A single file accomplishes the same, but it will be quite long depending on cluster size.

If the file(s) represents token ranges assigned to each node in the ring at the time of backup, it will be possible to create a 1-1 restore in the event of total failure. Since we assume the environment is AWS, IPs are good enough to represent the individual nodes. 

However, including hostnames would be good for environments where static, internal IP is not supported (e.g. Google Compute Engine). Speaking of GCE, we could add [Google Nearline storage](https://cloud.google.com/storage/docs/getting-started-gsutil) support and then this package would be doubly valuable compared to something like the [Python "cassandra_snapshotter"](https://github.com/tbarbugli/cassandra_snapshotter) module.

**Comment by iamthemovie** [comment]
Thanks for the feedback.

I have implemented a version locally that matches hostnames to IP's sand for the files, it stores separate files against each host name with a list of the token ranges in.

I will be pushing it up sometime tomorrow once I've tested it. 

As for the GCS, I'm happy to look at this after this next update!

**Comment by robusto** [comment]
Awesome! I'm happy to contribute code for GCS when I get some time. We may be moving from AWS to GCS (cheaper instances, faster storage).

**Comment by iamthemovie** [comment]
Yeah, I welcome the help! Interesting you say that, I'll definitely take a look at the price comparisons now that you mention it. 

Will tag the commit with this issue tomorrow.

Thanks again!

**Comment by robusto** [comment]
Some info I collected: https://goo.gl/0vVXDn  If your findings are different, please let me know. I also evaluated some others, but not worth mentioning right now.

**Comment by iamthemovie** [comment]
9853268988ddf36bb23ca46ee05c0753c85e6597 adds token backup.

**Comment by iamthemovie** [comment]
Let me know what you think, the output looks like this....

![image](https://cloud.githubusercontent.com/assets/369020/9139166/4f2cc444-3d20-11e5-885d-9d53cca74a80.png) 

and the file.... https://gist.github.com/iamthemovie/4bdc6bfa621951d817eb

**Comment by iamthemovie** [comment]
Commented: https://gist.github.com/iamthemovie/4bdc6bfa621951d817eb

Perhaps keep the conversation here so we get notifications?

**Comment by robusto** [comment]
Ah yes of course. I agree with your reasoning. We can always redress this when the time comes.
